export const ADD_MESSAGE = "ADD_MESSAGE";
export const POST_MESSAGE = "POST_MESSAGE";
export const STORE_MESSAGE_CONFIRMATION = "STORE_MESSAGE_CONFIRMATION";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const EMIT_SOCKET_EVENT = "EMIT_SOCKET_EVENT";
